export const defaultProps = {
	activeIndex: 0,
	animationDuration: 400,
	animationEasingFunction: 'ease',
	animationType: 'slide',
	autoHeight: false,
	autoWidth: false,
	autoPlay: false,
	autoPlayDirection: 'ltr',
	autoPlayInterval: 400,
	cancelAutoPlayOnAction: false,
	cancelAutoPlayOnHover: false,
	children: undefined,
	controlsStrategy: 'default',
	disableButtonsControls: false,
	disableDotsControls: false,
	disablePlayButtonControls: true,
	disableSlideInfo: true,
	infinite: false,
	items: undefined,
	mouseTracking: false,
	paddingLeft: 0,
	paddingRight: 0,
	responsive: undefined,
	swipeDelta: 20,
	swipeExtraPadding: 200,
	touchTracking: true,
	touchMoveDefaultEvents: true,
	onInitialized: () => undefined,
	onResized: () => undefined,
	onResizeEvent: undefined,
	onSlideChange: () => undefined,
	onSlideChanged: () => undefined,
};
