export const defaultProps = {
	children: [],
	items: [],
	infinite: false,
	showSlideInfo: false,
	dotsDisabled: false,
	buttonsDisabled: false,
	playButtonEnabled: false,
	controlsStrategy: 'default',
	autoPlayDirection: 'ltr',
	autoPlayInterval: 250,
	autoWidth: false,
	autoHeight: false,
	autoPlay: false,
	transitionDuration: 800,
	stopAutoPlayOnHover: true,
	preservePosition: false,
	startIndex: 0,
	onInitialized: () => undefined,
	onSlideChange: () => undefined,
};
